name: Android Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2
    - name: set up JDK 18
      uses: actions/setup-java@v3.5.1
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with gradle
      uses: gradle/gradle-build-action@v2.3.2
      with:
        arguments: test
