name: Android CI

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build debug apk
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3.0.2

      - name: set up JDK 18
        uses: actions/setup-java@v3.5.1
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.3.2
        with:
          arguments: assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v3.1.0
        if: ${{ !github.head_ref }}
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
